### ISSUE TITLE
Ver. 1.2.4 (FORGE) Crashes in 1.19.2 (Error in Server Tick Loop)

### ISSUE THREAD

**Issue by Tursiops-G** [Pitan76/UncraftingTable#25]
[Uncrafting Table Crash.txt](https://github.com/Pitan76/UncraftingTable/files/11056441/Uncrafting.Table.Crash.txt)

**Comment by suittizihou** [comment]
同じエラーが自分の環境でも表示されました。
下記はクラッシュレポートです。

---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-04-20 00:16:38
Description: Exception in server tick loop

java.lang.NoSuchFieldError: inventory
	at ml.pkom.uncraftingtable.InsertSlot.setOutStack(InsertSlot.java:174) ~[UncraftingTable-forge-1.2.4.jar%23202!/:?] {re:classloading}
	at ml.pkom.uncraftingtable.InsertSlot.updateOutSlot(InsertSlot.java:135) ~[UncraftingTable-forge-1.2.4.jar%23202!/:?] {re:classloading}
	at ml.pkom.uncraftingtable.InsertSlot.callSetStack(InsertSlot.java:166) ~[UncraftingTable-forge-1.2.4.jar%23202!/:?] {re:classloading}
	at ml.pkom.mcpitanlibarch.api.gui.slot.CompatibleSlot.m_5852_(CompatibleSlot.java:35) ~[mcpitanlibarch-1.6.3-1.19.2-forge.jar%23193!/:?] {re:classloading}
	at net.minecraft.world.inventory.Slot.m_150656_(Slot.java:166) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:409) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:293) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B}
	at ml.pkom.mcpitanlibarch.api.gui.SimpleScreenHandler.overrideOnSlotClick(SimpleScreenHandler.java:219) ~[mcpitanlibarch-1.6.3-1.19.2-forge.jar%23193!/:?] {re:classloading}
	at ml.pkom.mcpitanlibarch.api.gui.SimpleScreenHandler.m_150399_(SimpleScreenHandler.java:215) ~[mcpitanlibarch-1.6.3-1.19.2-forge.jar%23193!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1636) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.lambda$checkThreadAndEnqueue$0(PacketUtils.java:40) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading,xf:OptiFine:default}
	at net.optifine.util.PacketRunnable.run(PacketRunnable.java:28) ~[OptiFine_1.19.2_HD_U_I1.jar%23223!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:198) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:163) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:176) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23203!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:833) [?:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 15216506248 bytes (14511 MiB) / 17179869184 bytes (16384 MiB) up to 17179869184 bytes (16384 MiB)
	CPUs: 16
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 7 5800X 8-Core Processor             
	Identifier: AuthenticAMD Family 25 Model 33 Stepping 2
	Microarchitecture: Zen 3
	Frequency (GHz): 3.79
	Number of physical packages: 1
	Number of physical CPUs: 8
	Number of logical CPUs: 16
	Graphics card #0 name: NVIDIA GeForce RTX 3080 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2208
	Graphics card #0 versionInfo: DriverVersion=31.0.15.3141
	Memory slot #0 capacity (MB): 32768.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 32768.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 72189.16
	Virtual memory used (MB): 63555.44
	Swap memory total (MB): 6730.89
	Swap memory used (MB): 108.73
	JVM Flags: 12 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xms16G -Xmx16G -XX:MaxNewSize=4G -XX:MetaspaceSize=4G -XX:MaxMetaspaceSize=4G -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:ParallelGCThreads=12 -XX:ConcGCThreads=12 -XX:+DisableExplicitGC
	Server Running: true
	Player Count: 1 / 8; [ServerPlayer['suittizihou'/106, l='ServerLevel[テスト用]', x=-443.20, y=65.00, z=-1366.89]]
	Data Packs: vanilla, mod:mineallsmp (incompatible), mod:digallsmp (incompatible), mod:forge, mod:quarryplus, mod:cutallsmp (incompatible), mod:journeymap (incompatible), mod:jei (incompatible), mod:mekanism, mod:mekanismgenerators, mod:libipn (incompatible), mod:inventoryprofilesnext (incompatible), mod:architectury (incompatible), mod:lightoverlay (incompatible), mod:cloth_config (incompatible), mod:kotlinforforge (incompatible), mod:ironchest (incompatible), mod:industrialforegoing (incompatible), mod:titanium (incompatible), mod:gravestone (incompatible), mod:refinedstorage, mod:travelersbackpack, mod:crafttweaker (incompatible), mod:ae2 (incompatible), mod:toolleveling, mod:mcpitanlibarch (incompatible), mod:mekanismtools, mod:uncraftingtable76 (incompatible)
	World Generation: Experimental
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'; Server brand changed to 'forge'
	Launched Version: 1.19.2-forge-43.2.0
	OptiFine Version: OptiFine_1.19.2_HD_U_I1
	OptiFine Build: 20221213-150857
	Render Distance Chunks: 16
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 531.41
	OpenGlRenderer: NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 16
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.2.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		javafml@null
		kotlinforforge@3.11.0
		lowcodefml@null
		kotori_scala@2.13.10-build-10
	Mod List: 
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |DONE      |Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		industrial-foregoing-1.19.2-3.3.2.3-5.jar         |Industrial Foregoing          |industrialforegoing           |3.3.2.3             |DONE      |Manifest: NOSIGNATURE
		libIPN-forge-1.19-2.0.4.jar                       |libIPN                        |libipn                        |2.0.4               |DONE      |Manifest: NOSIGNATURE
		titanium-1.19.2-3.7.3-27.jar                      |Titanium                      |titanium                      |3.7.3               |DONE      |Manifest: NOSIGNATURE
		AdditionalEnchantedMiner-1.19.2-1192.1.0.jar      |QuarryPlus                    |quarryplus                    |1192.1.0            |DONE      |Manifest: 1a:13:52:63:6f:dc:0c:ad:7f:8a:64:ac:46:58:8a:0c:90:ea:2c:5d:11:ac:4c:d4:62:85:c7:d1:00:fa:9c:76
		[1.19.2][forge43.1.1]mod_CutAllSMP_v2.5.2.jar     |CutAll SMP                    |cutallsmp                     |2.5.2               |DONE      |Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.6.0.1013.jar                  |Just Enough Items             |jei                           |11.6.0.1013         |DONE      |Manifest: NOSIGNATURE
		appliedenergistics2-forge-12.9.3.jar              |Applied Energistics 2         |ae2                           |12.9.3              |DONE      |Manifest: NOSIGNATURE
		kffmod-3.11.0.jar                                 |Kotlin For Forge              |kotlinforforge                |3.11.0              |DONE      |Manifest: NOSIGNATURE
		gravestone-1.19.2-1.0.1.jar                       |Gravestone Mod                |gravestone                    |1.19.2-1.0.1        |DONE      |Manifest: NOSIGNATURE
		journeymap-1.19.2-5.9.5-forge.jar                 |Journeymap                    |journeymap                    |5.9.5               |DONE      |Manifest: NOSIGNATURE
		mcpitanlibarch-1.6.3-1.19.2-forge.jar             |MCPitanLib                    |mcpitanlibarch                |1.6.3-1.19.2-forge  |DONE      |Manifest: NOSIGNATURE
		TravelersBackpack-1.19.2-8.2.20.jar               |Traveler's Backpack           |travelersbackpack             |8.2.20              |DONE      |Manifest: NOSIGNATURE
		toolleveling-forge-1.19.2-1.4.1.jar               |Tool Leveling                 |toolleveling                  |1.19.2-1.4.1        |DONE      |Manifest: NOSIGNATURE
		InventoryProfilesNext-forge-1.19-1.9.5.jar        |Inventory Profiles Next       |inventoryprofilesnext         |1.9.5               |DONE      |Manifest: NOSIGNATURE
		architectury-6.5.77-forge.jar                     |Architectury                  |architectury                  |6.5.77              |DONE      |Manifest: NOSIGNATURE
		light-overlay-7.0.1-forge.jar                     |Light Overlay                 |lightoverlay                  |7.0.1               |DONE      |Manifest: NOSIGNATURE
		[1.19.2][forge43.1.1]mod_MineAllSMP_v2.6.6.jar    |MineAll SMP                   |mineallsmp                    |2.6.7               |DONE      |Manifest: NOSIGNATURE
		CraftTweaker-forge-1.19.2-10.1.41.jar             |CraftTweaker                  |crafttweaker                  |10.1.41             |DONE      |Manifest: NOSIGNATURE
		Mekanism-1.19.2-10.3.8.477.jar                    |Mekanism                      |mekanism                      |10.3.8              |DONE      |Manifest: NOSIGNATURE
		MekanismTools-1.19.2-10.3.8.477.jar               |Mekanism: Tools               |mekanismtools                 |10.3.8              |DONE      |Manifest: NOSIGNATURE
		MekanismGenerators-1.19.2-10.3.8.477.jar          |Mekanism: Generators          |mekanismgenerators            |10.3.8              |DONE      |Manifest: NOSIGNATURE
		[1.19.2][forge43.1.1]mod_DigAllSMP_v2.3.3.jar     |DigAll SMP                    |digallsmp                     |2.3.3               |DONE      |Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |DONE      |Manifest: NOSIGNATURE
		forge-1.19.2-43.2.0-universal.jar                 |Forge                         |forge                         |43.2.0              |DONE      |Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		refinedstorage-1.11.6.jar                         |Refined Storage               |refinedstorage                |1.11.6              |DONE      |Manifest: NOSIGNATURE
		ironchest-1.19.2-14.2.7.jar                       |Iron Chests                   |ironchest                     |1.19.2-14.2.7       |DONE      |Manifest: NOSIGNATURE
		UncraftingTable-forge-1.2.4.jar                   |Uncrafting Table              |uncraftingtable76             |1.2.4               |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: a0bc8be2-3966-4923-b298-fb6f75e270e0
	FML: 43.2
	Forge: net.minecraftforge:43.2.0

**Comment by PTOM76** [comment]
It's probably a bug similar to this one. Since there are many issues, I will close it for clarity. #30
