### ISSUE TITLE
Crash when putting item in Uncrafting Table[1.19.4 Forge-45.0.50][Mod version UncraftingTable-forge-1.2.4]

### ISSUE THREAD

**Issue by ghost** [Pitan76/UncraftingTable#30]
Game crashes when putting an item in the uncrafting table
java.lang.NoSuchFieldError: inventory
	at ml.pkom.uncraftingtable.InsertSlot.setOutStack(InsertSlot.java:174) ~[UncraftingTable-forge-1.2.4.jar%23157!/:?] {re:classloading}
	at ml.pkom.uncraftingtable.InsertSlot.updateOutSlot(InsertSlot.java:135) ~[UncraftingTable-forge-1.2.4.jar%23157!/:?] {re:classloading}
	at ml.pkom.uncraftingtable.InsertSlot.callSetStack(InsertSlot.java:166) ~[UncraftingTable-forge-1.2.4.jar%23157!/:?] {re:classloading}
	at ml.pkom.mcpitanlibarch.api.gui.slot.CompatibleSlot.m_269060_(CompatibleSlot.java:35) ~[mcpitanlibarch-1.6.3-1.19.4-forge.jar%23156!/:?] {re:classloading}
	at net.minecraft.world.inventory.Slot.m_150656_(Slot.java:165) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150430_(AbstractContainerMenu.java:410) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:294) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading}
	at ml.pkom.mcpitanlibarch.api.gui.SimpleScreenHandler.overrideOnSlotClick(SimpleScreenHandler.java:219) ~[mcpitanlibarch-1.6.3-1.19.4-forge.jar%23156!/:?] {re:classloading}
	at ml.pkom.mcpitanlibarch.api.gui.SimpleScreenHandler.m_150399_(SimpleScreenHandler.java:215) ~[mcpitanlibarch-1.6.3-1.19.4-forge.jar%23156!/:?] {re:classloading}
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1543) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading}
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:773) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:162) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:756) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:750) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:735) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:668) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:252) ~[client-1.19.4-20230314.122934-srg.jar%23158!/:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Thread.java:833) ~[?:?] {}

**Comment by HoodBlah** [comment]
I also have the same issue.
[debug.log](https://github.com/Pitan76/UncraftingTable/files/11410544/debug.log)
[latest.log](https://github.com/Pitan76/UncraftingTable/files/11410545/latest.log)

**Comment by HoodBlah** [comment]
The error message you provided suggests that there is a problem with a Minecraft mod called "Uncrafting Table". The error is related to a missing field called "inventory", which is causing the code to fail.

Here is the relevant part of the error message:

```
java.lang.NoSuchFieldError: inventory
	at ml.pkom.uncraftingtable.InsertSlot.setOutStack(InsertSlot.java:174) ~[UncraftingTable-forge-1.2.4.jar%23373!/:?]
	at ml.pkom.uncraftingtable.InsertSlot.updateOutSlot(InsertSlot.java:135) ~[UncraftingTable-forge-1.2.4.jar%23373!/:?]
	at ml.pkom.uncraftingtable.InsertSlot.callSetStack(InsertSlot.java:166) ~[UncraftingTable-forge-1.2.4.jar%23373!/:?]
```

The error occurs when the `setOutStack()` method of the `InsertSlot` class is called, which in turn calls the `updateOutSlot()` and `callSetStack()` methods. It seems that the `inventory` field that these methods rely on is not present, hence the `NoSuchFieldError` exception.

To fix this issue, you may need to update the Uncrafting Table mod to a newer version that includes the missing `inventory` field. Alternatively, you could try reaching out to the mod author for support or look for solutions on forums or other community resources for Minecraft modding.

**Comment by eldediamante** [comment]
Same error here!

**Comment by PTOM76** [comment]
Thank you for reporting.
Oddly enough, there seems to be a bug that the Extend Class cannot use the functions of the super class.
First of all, this is caused by MCPitanLib, which is compatible with both Forge and Fabric.
